language:   r
sudo:   false
cache:  packages

before_install:
    - tlmgr install inconsolata

os:
    - linux
    - osx

r_packages:
    - covr

after_success:
    - Rscript -e 'library(covr); codecov()'
