// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// select_controls_cpp
List select_controls_cpp(NumericMatrix& gmatrix, NumericVector& residuals, NumericMatrix& cc, NumericVector& chi2fn, NumericVector min_lambda, NumericVector lb_lambda, NumericVector max_lambda, NumericVector ub_lambda, IntegerVector min, IntegerVector bin_size);
RcppExport SEXP _SVDFunctions_select_controls_cpp(SEXP gmatrixSEXP, SEXP residualsSEXP, SEXP ccSEXP, SEXP chi2fnSEXP, SEXP min_lambdaSEXP, SEXP lb_lambdaSEXP, SEXP max_lambdaSEXP, SEXP ub_lambdaSEXP, SEXP minSEXP, SEXP bin_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix& >::type gmatrix(gmatrixSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type residuals(residualsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type cc(ccSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type chi2fn(chi2fnSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type min_lambda(min_lambdaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lb_lambda(lb_lambdaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type max_lambda(max_lambdaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ub_lambda(ub_lambdaSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type min(minSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type bin_size(bin_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(select_controls_cpp(gmatrix, residuals, cc, chi2fn, min_lambda, lb_lambda, max_lambda, ub_lambda, min, bin_size));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SVDFunctions_select_controls_cpp", (DL_FUNC) &_SVDFunctions_select_controls_cpp, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_SVDFunctions(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
