# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

quality_control_impl <- function(case_counts) {
    .Call('_SVDFunctions_quality_control_impl', PACKAGE = 'SVDFunctions', case_counts)
}

select_controls_cpp <- function(gmatrix, residuals, cc, chi2fn, min_lambda, lb_lambda, max_lambda, ub_lambda, min, bin_size) {
    .Call('_SVDFunctions_select_controls_cpp', PACKAGE = 'SVDFunctions', gmatrix, residuals, cc, chi2fn, min_lambda, lb_lambda, max_lambda, ub_lambda, min, bin_size)
}

parse_vcf <- function(filename, samples, bad_positions, variants, DP, GQ, gmatrix, predictMissing, regions, binary_prefix) {
    .Call('_SVDFunctions_parse_vcf', PACKAGE = 'SVDFunctions', filename, samples, bad_positions, variants, DP, GQ, gmatrix, predictMissing, regions, binary_prefix)
}

parse_binary_file <- function(variants, samples, binary_file, metafile, requiredDP, requiredGQ) {
    .Call('_SVDFunctions_parse_binary_file', PACKAGE = 'SVDFunctions', variants, samples, binary_file, metafile, requiredDP, requiredGQ)
}

